### ISSUE TITLE
Camera connection issue

### ISSUE THREAD

**Issue by priyashkla** [skumra/robotic-grasping#30]
**I have launched the camera and output is like** 
NODES
  /camera/
    realsense2_camera (nodelet/nodelet)
    realsense2_camera_manager (nodelet/nodelet)

ROS_MASTER_URI=http://011602p0023.local:11311

process[camera/realsense2_camera_manager-1]: started with pid [26131]
process[camera/realsense2_camera-2]: started with pid [26132]
[ INFO] [1617368659.444530186]: Initializing nodelet with 8 worker threads.
[ INFO] [1617368659.487527704]: RealSense ROS v2.2.14
[ INFO] [1617368659.487555222]: Running with LibRealSense v2.35.2
[ INFO] [1617368659.513961826]:  
[ INFO] [1617368659.680539226]: Device with serial number 925622071435 was found.

[ INFO] [1617368659.680587294]: Device with physical ID 2-2-34 was found.
[ INFO] [1617368659.680608696]: Device with name Intel RealSense D435 was found.
[ INFO] [1617368659.681496020]: Device with port number 2-2 was found.
[ INFO] [1617368659.686264464]: getParameters...
[ INFO] [1617368659.902394120]: setupDevice...

****I am assuming 925622071435  is device id and changing device id with 925622071435 in run_callibration and camera.py. And then running**** 

[baxter - http://011602p0023.local:11311] baxter@baxter:~/catkin_ws/src/robotic-grasping$ python run_calibration.py 
Traceback (most recent call last):
  File "run_calibration.py", line 13, in <module>
    calibration.run()
  File "/home/baxter/catkin_ws/src/robotic-grasping/hardware/calibrate_camera.py", line 112, in run
    self.camera.connect()
  File "/home/baxter/catkin_ws/src/robotic-grasping/hardware/camera.py", line 32, in connect
    cfg = self.pipeline.start(config)
RuntimeError: No device connected

**Help me if i am missing something.**

**Comment by skumra** [comment]
Are you using a ROS node for camera? The current code doesn't support ROS and that's why it is unable to connect to the camera/device.

**Comment by Tranthanhbao198** [comment]
> Are you using a ROS node for camera? The current code doesn't support ROS and that's why it is unable to connect to the camera/device.

hi, I donot use ros, i got same error: 
Traceback (most recent call last):
  File "/home/apicoo/robotic-grasping/run_realtime.py", line 40, in <module>
    cam.connect()
  File "/home/apicoo/robotic-grasping/hardware/camera.py", line 32, in connect
    cfg = self.pipeline.start(config)
RuntimeError: No device connected
please help me to fix
