### ISSUE TITLE
AttributeError: Couldn't find function center in BoundingBoxes or BoundingBox

### ISSUE THREAD

**Issue by CHB-learner** [skumra/robotic-grasping#64]
after 

python train_network.py --dataset cornell --dataset-path /home/ubuntu/机械臂入门教程/DATASETS/Cornell_Grasping_Dataset --description training_cornell

root        : INFO     Beginning Epoch 00
Traceback (most recent call last):
  File "/home/ubuntu/机械臂入门教程/robotic-grasping/train_network.py", line 345, in <module>
    run()
  File "/home/ubuntu/机械臂入门教程/robotic-grasping/train_network.py", line 318, in run
    train_results = train(epoch, net, device, train_data, optimizer, args.batches_per_epoch, vis=args.vis)
  File "/home/ubuntu/机械臂入门教程/robotic-grasping/train_network.py", line 163, in train
    for x, y, _, _, _ in train_data:
  File "/home/ubuntu/miniconda3/envs/bot_play/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 634, in __next__
    data = self._next_data()
  File "/home/ubuntu/miniconda3/envs/bot_play/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1346, in _next_data
    return self._process_data(data)
  File "/home/ubuntu/miniconda3/envs/bot_play/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1372, in _process_data
    data.reraise()
  File "/home/ubuntu/miniconda3/envs/bot_play/lib/python3.9/site-packages/torch/_utils.py", line 644, in reraise
    raise exception
AttributeError: Caught AttributeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/bot_play/lib/python3.9/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/ubuntu/miniconda3/envs/bot_play/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/ubuntu/miniconda3/envs/bot_play/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/ubuntu/机械臂入门教程/robotic-grasping/utils/data/grasp_data.py", line 65, in __getitem__
    depth_img = self.get_depth(idx, rot, zoom_factor)
  File "/home/ubuntu/机械臂入门教程/robotic-grasping/utils/data/cornell_data.py", line 52, in get_depth
    center, left, top = self._get_crop_attrs(idx)
  File "/home/ubuntu/机械臂入门教程/robotic-grasping/utils/data/cornell_data.py", line 37, in _get_crop_attrs
    center = gtbbs.center
  File "/home/ubuntu/机械臂入门教程/robotic-grasping/utils/dataset_processing/grasp.py", line 43, in __getattr__
    raise AttributeError("Couldn't find function %s in BoundingBoxes or BoundingBox" % attr)
AttributeError: Couldn't find function center in BoundingBoxes or BoundingBox

**Comment by destroy314** [comment]
I have encountered this before, I think it may be caused by the too-high version of python or some packages, and the problem was solved after configuring the environment using the command below.
https://github.com/skumra/robotic-grasping/issues/57#issuecomment-1540322748

**Comment by zhenjing** [comment]
refer to: https://github.com/zhenjing/robotic-grasping
